In [30]:
import pandas as pd
A = pd.read_csv("C:/Users/Asus/Downloads/Train (big mart).csv")
A

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

In [31]:
A.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8523 entries, 0 to 8522
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Item_Identifier            8523 non-null   object
 1   Item_Weight                7060 non-null   float64
 2   Item_Fat_Content           8523 non-null   object
 3   Item_Visibility            8523 non-null   float64
 4   Item_Type                  8523 non-null   object
 5   Item_MRP                   8523 non-null   float64
 6   Outlet_Identifier          8523 non-null   object
 7   Outlet_Establishment_Year  8523 non-null   int64
 8   Outlet_Size                6113 non-null   object
 9   Outlet_Location_Type       8523 non-null   object
 10  Outlet_Type                8523 non-null   object
 11  Item_Outlet_Sales          8523 non-null   float64
dtypes: float64(4), int64(1), object(7)
memory usage: 799.2+ KB

In [32]:
A.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [33]:
from google.colab import files

In [5]:
files.upload()

Saving PM6.py to PM6.py

{'PM6.py': b'def ANOVA(df,cat,con):\n    from statsmodels.formula.api import ols\n    relation = con + " ~ " + cat\n    model = ols(relation,df).fit()\n    from statsmodels.stats.anova import anova_lm\n    anova_results = anova_lm(model)\n    return round(anova_results.iloc[0,4],4)\n\ndef replacer(df):\n    import pandas as pd\n    Q = pd.DataFrame(df.isna().sum(),columns=["ct"])\n    for i in Q[Q.ct > 0].index:\n        if(df[i].dtypes == "object"):\n            x = df[i].mode()[0]\n            df[i] = df[i].fillna(x)\n        else:\n            x = df[i].mean()\n            df[i] = df[i].fillna(x)\n            \ndef preprocessing(df):\n    import pandas as pd\n    cat = []\n    con = []\n    for i in df.columns:\n        if(df[i].dtypes == "object"):\n            cat.append(i)\n        else:\n            con.append(i)\n    X1 = pd.get_dummies(df[cat])\n    from sklearn.preprocessing import StandardScaler\n    ss = StandardScaler()\n    X2 = pd.DataFrame(ss.fit_transform(df[con]),columns=con)\n    X3 = X2.join(X1)\n    return X3\n\ndef chisq(df,cat1,cat2):\n    import pandas as pd\n    from scipy.stats import chi2_contingency\n    ct = pd.crosstab(df[cat1],df[cat2])\n    a,b,c,d = chi2_contingency(ct)\n    return b\n\ndef seperate(df):\n    con = []\n    cat = []\n    for i in df.columns:\n        if (df[i].dtypes == "object"):\n            cat.append(i)\n        else:\n            con.append(i)\n            \n    return con,cat\n\n \n'}

In [34]:
from PM6 import replacer
replacer(A)

In [35]:
A.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [36]:
Y = A[["Item_Outlet_Sales"]]

In [37]:
A.corr()["Item_Outlet_Sales"]

Item_Weight                  0.011550
Item_Visibility             -0.128625
Item_MRP                     0.567574
Outlet_Establishment_Year   -0.049135
Item_Outlet_Sales            1.000000
Name: Item_Outlet_Sales, dtype: float64

# **ANOVA**

In [ ]:
files.upload()

In [38]:
#catcon
def catcon(df):
  cat=[]
  con=[]
  for i in df.columns:
    if df[i].dtypes=="object":
      cat.append(i)
    else:
      con.append(i)
  return cat,con


def anova_con(df,con_col):
  cat,con=catcon(df)
  from statsmodels.formula.api import ols
  from statsmodels.stats.anova import anova_lm
  imp_cat=[]
  for i in cat:
    reg=con_col+"~"+i
    model=ols(reg,df).fit()
    results=anova_lm(model)
    print("---------------------",con_col,"vs",i,"----------------------------")
    print("pvalue: ",results.iloc[0,4])
    if results.iloc[0,4]<0.05:
      imp_cat.append(i)
  print("\n","Important Categorical features: ",imp_cat)
  return imp_cat

In [39]:
anova_con(A,"Item_Outlet_Sales")

--------------------- Item_Outlet_Sales vs Item_Identifier ----------------------------
pvalue:  1.2735307576391993e-252
--------------------- Item_Outlet_Sales vs Item_Fat_Content ----------------------------
pvalue:  0.14122147854932424
--------------------- Item_Outlet_Sales vs Item_Type ----------------------------
pvalue:  0.00038843993766479187
--------------------- Item_Outlet_Sales vs Outlet_Identifier ----------------------------
pvalue:  0.0
--------------------- Item_Outlet_Sales vs Outlet_Size ----------------------------
pvalue:  9.642803947830672e-19
--------------------- Item_Outlet_Sales vs Outlet_Location_Type ----------------------------
pvalue:  5.2228172988842975e-24
--------------------- Item_Outlet_Sales vs Outlet_Type ----------------------------
pvalue:  0.0

 Important Categorical features:  ['Item_Identifier', 'Item_Type', 'Outlet_Identifier', 'Outlet_Size', 'Outlet_Location_Type', 'Outlet_Type']

['Item_Identifier',
 'Item_Type',
 'Outlet_Identifier',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [40]:
X=A[['Item_Type',
 'Outlet_Identifier',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type',"Item_MRP","Item_Weight"]]

In [41]:
#X = A.drop(columns = ["Item_Weight","Item_Visibility","Outlet_Establishment_Year","Item_Outlet_Sales","Item_Identifier","Item_Fat_Content"])

In [42]:
from PM6 import preprocessing
Xnew = preprocessing(X)

In [43]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size = 0.2,random_state = 21)

from statsmodels.api import OLS,add_constant
xconst = add_constant(xtrain)
ols = OLS(ytrain,xconst)
model = ols.fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:      Item_Outlet_Sales   R-squared:                       0.564
Model:                            OLS   Adj. R-squared:                  0.563
Method:                 Least Squares   F-statistic:                     338.2
Date:                Thu, 08 Sep 2022   Prob (F-statistic):               0.00
Time:                        05:41:49   Log-Likelihood:                -57596.
No. Observations:                6818   AIC:                         1.152e+05
Df Residuals:                    6791   BIC:                         1.154e+05
Df Model:                          26
Covariance Type:            nonrobust
===================================================================================================
                                      coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
const                            8.509e+13   2.61e+14      0.327      0.744   -4.26e+14    5.96e+14
Item_MRP                          968.5895     13.746     70.465      0.000     941.643     995.535
Item_Weight                         2.9488     13.796      0.214      0.831     -24.095      29.993
Item_Type_Baking Goods           2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Breads                 2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Breakfast              2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Canned                 2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Dairy                  2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Frozen Foods           2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Fruits and Vegetables  2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Hard Drinks            2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Health and Hygiene     2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Household              2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Meat                   2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Others                 2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Seafood                2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Snack Foods            2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Soft Drinks            2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Item_Type_Starchy Foods          2.359e+13   7.22e+13      0.327      0.744   -1.18e+14    1.65e+14
Outlet_Identifier_OUT010         2.983e+14   9.13e+14      0.327      0.744   -1.49e+15    2.09e+15
Outlet_Identifier_OUT013        -3.437e+14   1.05e+15     -0.327      0.744   -2.41e+15    1.72e+15
Outlet_Identifier_OUT017         9.309e+13   2.85e+14      0.327      0.744   -4.66e+14    6.52e+14
Outlet_Identifier_OUT018         3.253e+14   9.96e+14      0.327      0.744   -1.63e+15    2.28e+15
Outlet_Identifier_OUT019         4.676e+13   1.43e+14      0.327      0.744   -2.34e+14    3.27e+14
Outlet_Identifier_OUT027         3.146e+14   9.63e+14      0.327      0.744   -1.57e+15     2.2e+15
Outlet_Identifier_OUT035        -2.201e+14   6.74e+14     -0.327      0.744   -1.54e+15     1.1e+15
Outlet_Identifier_OUT045         9.309e+13   2.85e+14      0.327      0.744   -4.66e+14    6.52e+14
Outlet_Identifier_OUT046        -2.261e+14   6.93e+14     -0.327      0.744   -1.58e+15    1.13e+15
Outlet_Identifier_OUT049         8.706e+13   2.67e+14      0.327      0.744   -4.36e+14     6.1e+14
Outlet_Size_High                -3.446e+14   1.06e+15     -0.327      0.744   -2.41e+15    1.72e+15
Outlet_Size_Medium              -7.136e+14   2.19e+15     -0.327      0.744      -5e+15    3.57e+15
Outlet_Size_Small               -4.004e+14   1.23e+15     -0.327      0.744    -2.8e+15       2e+15
Outlet_Location_Type_Tier 1     -8.435e+13   2.58e+14     -0.327      0.744   -5.91e+14    4.22e+14
Outlet_Location_Type_Tier 2     -9.038e+13   2.77e+14     -0.327      0.744   -6.33e+14    4.52e+14
Outlet_Location_Type_Tier 3     -2.265e+13   6.94e+13     -0.327      0.744   -1.59e+14    1.13e+14
Outlet_Type_Grocery Store        3.293e+14   1.01e+15      0.327      0.744   -1.65e+15    2.31e+15
Outlet_Type_Supermarket Type1    6.022e+14   1.84e+15      0.327      0.744   -3.01e+15    4.22e+15
Outlet_Type_Supermarket Type2    3.022e+14   9.25e+14      0.327      0.744   -1.51e+15    2.12e+15
Outlet_Type_Supermarket Type3     3.13e+14   9.58e+14      0.327      0.744   -1.57e+15    2.19e+15
==============================================================================
Omnibus:                      815.672   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2059.432
Skew:                           0.685   Prob(JB):                         0.00
Kurtosis:                       5.318   Cond. No.                     1.88e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 4.84e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

# **Model 1 (Best Model)**

In [44]:
from warnings import filterwarnings
filterwarnings("ignore")

drop_cols = list(model.pvalues.sort_values().index)[-1]
print("dropped_column:",drop_cols,"\n")
Xnew = Xnew.drop(labels=[drop_cols],axis=1)
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size = 0.2,random_state = 21)

from statsmodels.api import OLS,add_constant
xconst = add_constant(xtrain)
ols = OLS(ytrain,xconst)
model = ols.fit()
print("--------------------------------------------------------")
print("Adjusted Rsquared",round(model.rsquared_adj,5))
print("Rsquared",round(model.rsquared,5))
print("--------------------------------------------------------")

dropped_column: Item_Weight

--------------------------------------------------------
Adjusted Rsquared 0.56266
Rsquared 0.56427
--------------------------------------------------------

# **Model 2**

In [27]:
"""from warnings import filterwarnings
filterwarnings("ignore")

drop_cols = list(model.pvalues.sort_values().index)[-1]
print("dropped_column:",drop_cols,"\n")
Xnew = Xnew.drop(labels=[drop_cols],axis=1)
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size = 0.2,random_state = 21)

from statsmodels.api import OLS,add_constant
xconst = add_constant(xtrain)
ols = OLS(ytrain,xconst)
model = ols.fit()
print("--------------------------------------------------------")
print("Adjusted Rsquared",round(model.rsquared_adj,5))
print("Rsquared",round(model.rsquared,5))
print("--------------------------------------------------------")"""

dropped_column: Outlet_Identifier_OUT018

--------------------------------------------------------
Adjusted Rsquared 0.56265
Rsquared 0.56426
--------------------------------------------------------

# **Model 3**

In [28]:
"""from warnings import filterwarnings
filterwarnings("ignore")

drop_cols = list(model.pvalues.sort_values().index)[-1]
print("dropped_column:",drop_cols,"\n")
Xnew = Xnew.drop(labels=[drop_cols],axis=1)
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size = 0.2,random_state = 21)

from statsmodels.api import OLS,add_constant
xconst = add_constant(xtrain)
ols = OLS(ytrain,xconst)
model = ols.fit()
print("--------------------------------------------------------")
print("Adjusted Rsquared",round(model.rsquared_adj,5))
print("Rsquared",round(model.rsquared,5))
print("--------------------------------------------------------")"""

dropped_column: Outlet_Type_Supermarket Type2

--------------------------------------------------------
Adjusted Rsquared 0.56265
Rsquared 0.56426
--------------------------------------------------------

# **Model 4**

In [29]:
"""from warnings import filterwarnings
filterwarnings("ignore")

drop_cols = list(model.pvalues.sort_values().index)[-1]
print("dropped_column:",drop_cols,"\n")
Xnew = Xnew.drop(labels=[drop_cols],axis=1)
xtrain,xtest,ytrain,ytest = train_test_split(Xnew,Y,test_size = 0.2,random_state = 21)

from statsmodels.api import OLS,add_constant
xconst = add_constant(xtrain)
ols = OLS(ytrain,xconst)
model = ols.fit()
print("--------------------------------------------------------")
print("Adjusted Rsquared",round(model.rsquared_adj,5))
print("Rsquared",round(model.rsquared,5))
print("--------------------------------------------------------")"""

dropped_column: Outlet_Identifier_OUT035

--------------------------------------------------------
Adjusted Rsquared 0.56259
Rsquared 0.5642
--------------------------------------------------------

In [45]:
Xnew

,Item_MRP,Item_Type_Baking Goods,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,Item_Type_Fruits and Vegetables,Item_Type_Hard Drinks,Item_Type_Health and Hygiene,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,1.747454,0,0,0,0,1,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
1,-1.489023,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
2,0.010040,0,0,0,0,0,0,0,0,0,...,0,1,0,1,0,0,0,1,0,0
3,0.660050,0,0,0,0,0,0,1,0,0,...,0,1,0,0,0,1,1,0,0,0
4,-1.399220,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,1.180783,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,1,0,0
8519,-0.527301,1,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,0,1,0,0
8520,-0.897208,0,0,0,0,0,0,0,0,1,...,0,0,1,0,1,0,0,1,0,0
8521,-0.607977,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,1,0
8522,-1.052261,0,0,0,0,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0

In [46]:
X1 = list(Xnew.columns)
X1

['Item_MRP',
 'Item_Type_Baking Goods',
 'Item_Type_Breads',
 'Item_Type_Breakfast',
 'Item_Type_Canned',
 'Item_Type_Dairy',
 'Item_Type_Frozen Foods',
 'Item_Type_Fruits and Vegetables',
 'Item_Type_Hard Drinks',
 'Item_Type_Health and Hygiene',
 'Item_Type_Household',
 'Item_Type_Meat',
 'Item_Type_Others',
 'Item_Type_Seafood',
 'Item_Type_Snack Foods',
 'Item_Type_Soft Drinks',
 'Item_Type_Starchy Foods',
 'Outlet_Identifier_OUT010',
 'Outlet_Identifier_OUT013',
 'Outlet_Identifier_OUT017',
 'Outlet_Identifier_OUT018',
 'Outlet_Identifier_OUT019',
 'Outlet_Identifier_OUT027',
 'Outlet_Identifier_OUT035',
 'Outlet_Identifier_OUT045',
 'Outlet_Identifier_OUT046',
 'Outlet_Identifier_OUT049',
 'Outlet_Size_High',
 'Outlet_Size_Medium',
 'Outlet_Size_Small',
 'Outlet_Location_Type_Tier 1',
 'Outlet_Location_Type_Tier 2',
 'Outlet_Location_Type_Tier 3',
 'Outlet_Type_Grocery Store',
 'Outlet_Type_Supermarket Type1',
 'Outlet_Type_Supermarket Type2',
 'Outlet_Type_Supermarket Type3']

In [48]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest= train_test_split(Xnew,Y,test_size=0.2,random_state=21)

from sklearn.linear_model import LinearRegression
lm = LinearRegression()
model = lm.fit(xtrain,ytrain)
pred_tr = model.predict(xtrain)
pred_ts = model.predict(xtest)

from sklearn.metrics import mean_absolute_error
print("------------------------------------------------------")
print("Training Error: ",mean_absolute_error(ytrain,pred_tr))
print("Testing Error: ",mean_absolute_error(ytest,pred_ts))
print("------------------------------------------------------")

------------------------------------------------------
Training Error:  838.1130282780874
Testing Error:  831.0845703225807
------------------------------------------------------

**Model is Underfitting**

**When Testing Error is low in than Training Error then the model suffers from UNDERFITTING**

# **END**